version: "3"
services:
  sauce-connect-eu:
    image: "saucelabs/sauce-connect:latest"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    command: "run -i pdf-compose -r eu-central"

  sauce-connect-us:
    image: "saucelabs/sauce-connect:latest"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    command: "run -i pdf-compose -r us-west"

  simple-server:
    image: "simple-server"
    container_name: "simpleserver"
    ports:
      - "1080:1080"