version: "3"
services:
  sauce-connect:
    image: "saucelabs/sauce-connect:latest"
    container_name: "sc-eu-central"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    command: "-i composed-docker-sc -r eu-central"

  sauce-connect2:
    image: "saucelabs/sauce-connect:latest"
    container_name: "sc-us-west"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    command: "-i composed-docker-sc -r us-west"
  
  app-server:
    image: "simple-server"
    container_name: "simpleserver"
    ports:
      - "3333:1080"