version: "3"
services:
  sauce-connect-eu:
    image: "saucelabs/sauce-connect:latest"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    command: "run -i composed-docker-sc -r eu-central"
    
  nginx:
    image: "nginx:latest"
    container_name: "some-app"
    ports:
      - "3333:80"
