version: "3.9"
services:
  sauce-connect-eu:
    deploy:
      replicas: 2
      restart_policy:
        delay: 30s
        max_attempts: 5
        condition: on-failure
        window: 60s
    image: "saucelabs/sauce-connect:latest"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
      SAUCE_LOGFILE: /tmp/persistent-eu-proxy1.log
    command: "-i eu-pool -r eu-central --tunnel-pool"

  sauce-connect-us:
    image: "saucelabs/sauce-connect:latest"
    restart: on-failure:2
    deploy:
      replicas: 2
      restart_policy:
        delay: 30s
        max_attempts: 5
        condition: on-failure
        window: 60s
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    command: "-i us-pool -i docker-sc -r us-west --tunnel-pool"